### ISSUE TITLE
Minimum Pixel Dimension for YouTube Embed 

### ISSUE THREAD

**Issue by nashinmahtani** [urbanriskmap/petabencana.id#103]
@talltom I believe these are the minimum pixel dimensions for embedding the "How to Report" Video on the PetaBencana.id website (in case this might affect the design of the side bar)

![minimum pixel dimension for youtube embed](https://cloud.githubusercontent.com/assets/22739955/21798783/dc667e90-d748-11e6-91eb-9bef34e4f4a9.png)

**Comment by talltom** [comment]
ping @asbarve and @ojha-url.

**Comment by talltom** [comment]
@nashinmahtani on our smallest target device (iPhone 4s 320px x 480px) the available space in for video content embed is 304px so hoping this should be OK.
