### ISSUE TITLE
Add time stamps to reports

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/petabencana.id#104]
@talltom @matthewberryman , after testing the Telegram reports we checked the dev.petabencana.id and it goes online immediately, but it does not say it comes from Telegram and the time stamp (as well for other sources). Screenshots for comparison:

- Report from Telegram
![2017 01 10 17 06](https://cloud.githubusercontent.com/assets/22338984/21802685/4d1c1e46-d759-11e6-8119-dd9832065d5d.PNG)
 
- Report from Qlue (I noticed the source from the description)
![2017 01 10 16 16](https://cloud.githubusercontent.com/assets/22338984/21802712/6c4b73c0-d759-11e6-8f22-cbdaf2be1b3c.PNG)
*FYI reports from this area did not appear in PetaJakarta.org
![2017 01 10 17 24 pj](https://cloud.githubusercontent.com/assets/22338984/21802855/0d21ea7c-d75a-11e6-8dc0-085ad872a3dd.PNG)

 but other Qlue reports appeared in both PetaBencana.id and PetaJakarta.org:
![2017 01 10 17 25 pj](https://cloud.githubusercontent.com/assets/22338984/21802877/231b41d4-d75a-11e6-8e29-47a2f225cfee.PNG)
![2017 01 10 17 25](https://cloud.githubusercontent.com/assets/22338984/21802878/2324feae-d75a-11e6-889e-c85d480818ff.PNG)

cc: @fadmastuti @anexact 
Thank you!

**Comment by talltom** [comment]
Hi @prittandrani thanks for this! I edited the title to clarify the issue.

Regarding the data source of the report, because of space available and because we take reports from many different data sources I was thinking we wouldn't include the logo of the original report data source this year. In particular, because reports submitted via GRASP (Twitter and Telegram) are actually PetaBencana.id reports (they do not use data from Twitter or Telegram, but instead require the user to send us flood info via the report cards. We just use Twitter/Telegram to send the links). Let me know what you think. 👍

**Comment by prittandrani** [comment]
Hi @talltom for the GRASP I agree, in my opinion for other source than
GRASP it is best to display the logo to let user know if their reports are
in since they are not getting the link like what we do from the bot.
Or other options maybe we can have a tab showing the logo from our data
partners. I think we can handle that with the How to Report tab with the
local applications explanation. Will let you know if there's any follow up
comments especially from our partner. Thanks!

*---*
*Pritta Andrani Widyanarko*
Mobile: +62 856 9444 4444

On Tue, Jan 10, 2017 at 10:18 PM, Tomas Holderness <notifications@github.com

**Comment by talltom** [comment]
Time stamps have now been added to reports. Time stamps are always shown in Indonesian time (ICT/WIB).

<img width="440" alt="screen shot 2017-01-17 at 4 44 06 pm" src="https://cloud.githubusercontent.com/assets/944642/22041263/35c50b88-dcd4-11e6-9d23-cbf7b2129537.png">

**Comment by prittandrani** [comment]
Great, thank you so much @talltom!

*---*
*Pritta Andrani Widyanarko*
Mobile: +62 856 9444 4444

**Comment by prittandrani** [comment]
Great, thank you so much @talltom! I noticed that the time here is currently not matched with the clock? (my guess is it is 7 hours ahead?)

![20170118 _ time stamp report](https://cloud.githubusercontent.com/assets/22338984/22051019/7420f6d2-dd72-11e6-963c-0c1bee70baba.PNG)

Thank you! :)
