### ISSUE TITLE
Add a video to map pane

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#105]
- add map and how to report videos to map modal

**Comment by talltom** [comment]
Mock-up of drop down functionality for different videos by data source
http://jsfiddle.net/v170kjyu/2/

**Comment by talltom** [comment]
Reference point for new embedding method of youtube videos: https://developers.google.com/youtube/player_parameters

**Comment by ojha-url** [comment]
Requires video links.

**Comment by nashinmahtani** [comment]
@ojha-url Video links:

How to Make a Report (Bahasa Indonesia)
https://www.youtube.com/watch?v=Gb_BAAiRw2U

What is PetaBencana (Bahasa Indonesia)
https://www.youtube.com/watch?v=qddQUIelwQo

How to Make a Report (English)
https://www.youtube.com/watch?v=EfJRa9sF89Y

What is PetaBencana (English)
https://youtu.be/aO7-XNabFwY

**Comment by talltom** [comment]
Hi @nashinmahtani thanks for these. I have added the videos to the how to report section of the map side-pane. Will close this issue for now, we can continue discussions on whether to split videos at a later date.

Videos are now up on https://dev.petabencana.id
