### ISSUE TITLE
Cards broken?

### ISSUE THREAD

**Issue by fadmastuti** [urbanriskmap/petabencana.id#106]
<img width="1422" alt="screen shot 2017-01-11 at 10 37 54 am" src="https://cloud.githubusercontent.com/assets/2441950/21835675/821b9048-d7f1-11e6-8e5d-8544fb7dc945.png">

cc @talltom @matthewberryman @anexact

**Comment by talltom** [comment]
Hi Dika, card "123" is not a real card so you can't see it. I will follow up with an email regarding how to test cards.
