### ISSUE TITLE
Update promotional cover image for social media cards

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#112]
![2017-01-12 00 51 29](https://cloud.githubusercontent.com/assets/22597094/21872631/76d2e2a4-d837-11e6-9cf8-e11d3da0b9ec.png)

**Comment by ojha-url** [comment]
Thoughts? 
I would suggest a "curated" snapshot of REM enabled map, showing:
- styled mapbox base map from @asbarve 
- few report icons
- graded blue polygons

Need this by Friday, @asbarve can you mock one up in AI?

**Comment by asbarve** [comment]
Will send something tonight your morning

Map and icons may look muddled in small preview... our icon for flood image in cards could be used may be a photo or something

**Comment by ojha-url** [comment]
![3](https://cloud.githubusercontent.com/assets/22597094/21903210/fa5526c4-d8cc-11e6-9ccb-69e9b29a1bb8.png)

@talltom has a better suggestion, we should use this and make a graphic around it, also can use the finger-swipe svg we had in the previous version.

**Comment by talltom** [comment]
Hi @asbarve just wondering whether you're able to work on this at the current time? Thanks

**Comment by asbarve** [comment]
Hi @talltom I sent some alternatives couple of days ago - attaching a image here : decision needs to be made on which one. After that either I or Mayank can change the link in meta tags.
![170113_card_graphics_ab_small](https://cloud.githubusercontent.com/assets/18059215/22053067/55dde2dc-dd74-11e6-8bfa-1cada9ab0a37.png)
