### ISSUE TITLE
Clear report id from URL on city change

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#118]
Current case:
- Go to Jakarta, select report
- open side bar & change city
- map fits in New city bounds, then flies back to report in Jakarta because of persisting report id

**Comment by talltom** [comment]
@ojha-url I can't re-create this issue. It could have got fixed in a recent issue.

I'm going to close this issue until we can recreate.

**Comment by ojha-url** [comment]
Still glitching,
happens when a report is open in one city, and city is changed from the menu.
starts flyTo new city, then flies back to open report in previous city.

I'll look into it:
- set report_id to null on city change (when picked from menu)
- set report_id to null when user closes report popup manually (invoke pushstate)

**Comment by talltom** [comment]
Hi @ojha-url lets revisit this Tuesday.
