### ISSUE TITLE
display of buttons on iOS apps internal web browsers

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#130]
On iOS apps that have a bar at the bottom, the back and next page buttons (in our UI) won't display:
![img_2496](https://cloud.githubusercontent.com/assets/2288238/21925915/b06eb860-d9d3-11e6-8713-18c839e3cc6a.JPG)
@ojha-url did a quick fix to get us over the line to launch (along with some other last minute fixes, for which I owe him a coffee some time 👍 ), however the end result on iOS apps and browsers, while workable, is a bit ugly:
![img_2504](https://cloud.githubusercontent.com/assets/2288238/21925963/de05de66-d9d3-11e6-94a8-f6a77b0952f9.PNG)
This fix is low priority (certainly behind REM work)

**Comment by ojha-url** [comment]
Resources:
http://stackoverflow.com/questions/16383776/detect-in-app-browser-webview-with-php-javascript
http://stackoverflow.com/questions/35695229/how-to-determine-if-website-is-opened-on-iphone-android-browser-or-from-iphone-a

@talltom, need to document navigator.userAgent string for various cases in this thread (by adding an alert & doing test runs in twilio, telegram, twitter etc, on both iphone & android)

**Comment by ojha-url** [comment]
navigator.userAgent.toLowerCase()

- iPhone OS 10_0_2 (iPhone 5), safari browser:
mozilla/5.0 (iphone; cpu iphone os 10_0_2 like mac os x) applewebkit/602.1.50 (khtml, like gecko) version/10.0 mobile/14a456 safari/602.1

- Facebook messenger, in-app browser on iPhone OS 10_0_2 (iPhone 5):
mozilla/5.0 (iphone; cpu iphone os 10_0_2 like mac os x) applewebkit/602.1.50 (khtml, like gecko) mobile/14a456 [fban/messengerforos;fbav/101.0.0.29.338;fbbv/47728...

**Comment by talltom** [comment]
Looks like this is still occurring on prod, as reported by @anexact from within Twitter/Safari
![whatsapp image 2017-01-23 at 23 30 53](https://cloud.githubusercontent.com/assets/944642/22257702/d664aa0a-e22c-11e6-9138-ed4c589cb32f.jpeg)

**Comment by ojha-url** [comment]
**Manual testing for UI behaviour**

- **iPhone 4**
    - [ ] Twitter
    - [ ] Telegram
    - [ ] WhatsApp
    - [ ] Facebook
    - [ ] Messenger (facebook)

- iPhone 5s
    - [ ] Twitter
        - In-app, shrink height by 106px
    - [ ] Telegram
        - In-app (safari instance), no resize
    - [ ] WhatsApp
        - Safari, no resize
    - [ ] Facebook
        - In-app, shrink height by 106px
    - [ ] Messenger (facebook)
        - In-app, no resize

- **iPhone 6**
    - [ ] Twitter
    - [ ] Telegram
    - [ ] WhatsApp
    - [ ] Facebook
    - [ ] Messenger (facebook)

- **Android 6.0**
    - [ ] Twitter
        - In-app, no resize
    - [ ] Telegram
        - In-app (chrome instance), no resize
    - [ ] WhatsApp
        - Chrome, no resize
    - [ ] Facebook
        - In-app, no resize
    - [ ] Messenger (facebook) 
        - In-app, no resize
