### ISSUE TITLE
Web Menu How to Report steps text and translation

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/petabencana.id#132]
Hi all, in our last meeting with BNPB our partner suggest to put the steps to report besides the video in simple steps.
I and @fadmastuti provide the text here:

EN

Twitter:
1. Tweet #banjir to @petabencana.
2. Open the link and follow the instructions to input flood location, upload photo, and description.
3. You can see your report on the map via the link provided. Check PetaBencana.id for up-to-date flood information.

Telegram:
1. Text /banjir to @BencanaBot.
2. Open the link and follow the instructions to input flood location, upload photo, and description.
3. You can see your report on the map via the link provided. Check PetaBencana.id for up-to-date flood information.

Local applications
(We can use logos here or link it to the apps landing page)
1. You can report flood from Qlue, PasangMata, and Z-Alert.
2. Your report is now on the map. Check PetaBencana.id for up-to-date flood information.

Qlue: http://www.qlue.co.id/ 
PasangMata: http://pasangmata.detik.com/ 
Z-Alert: https://www.zurich.co.id/id-id/kampanye-kami/zurich-alert-the-alert-you-really-need 

-----
BI

Twitter:
1. Tweet #banjir ke @petabencana.
2. Buka linknya, dan ikuti panduan untuk menginput lokasi, foto, dan deskripsi.
3. Anda dapat melihat laporan Anda di peta lewat link balasan. Cek PetaBencana.id untuk info banjir terkini.

Telegram:
1. Kirim /banjir ke @BencanaBot.
2. Buka linknya, dan ikuti panduan untuk menginput lokasi, foto, dan deskripsi.
3. Anda dapat melihat laporan Anda di peta lewat link balasan. Cek PetaBencana.id untuk info banjir terkini.

Local applications
1. Anda dapat melapor lewat Qlue, PasangMata, dan Z-Alert.
2. Laporan Anda sudah tampil di peta. Cek PetaBencana.id untuk info banjir terkini.

Please review @anexact, cc @talltom @matthewberryman

**Comment by ojha-url** [comment]
Awaited confirmation from assigned reviewers.

**Comment by matthewberryman** [comment]
@ojha-url I'd already indicated to @prittandrani I'd work on this and I've already started; please work on other things like REM

**Comment by matthewberryman** [comment]
@ojha-url Ok I can see on other issues it looks like @talltom has fixed and I just need to deploy.

**Comment by matthewberryman** [comment]
(sorry I was getting confused between these two separate translation works due to tiredness and heat, please disregard my previous comment, @ojha-url )

**Comment by ojha-url** [comment]
@matthewberryman, no worries, thanks for clarifying!

**Comment by matthewberryman** [comment]
Ok, now I know what I'm doing, and just reviewing this before @ojha-url works on it:
* Photos should be singular "photo" in EN text. In BI I think it's fine (I don't think BI has a singular/plural distinction). @prittandrani 
* Given the bots reply with a specific link to the report on the map once it's up, maybe refer to that in this text (EN & BI would need changes)

**Comment by talltom** [comment]
Hi @prittandrani also wondering what the status of the videos to be embedded in the map is? Thanks

**Comment by prittandrani** [comment]
Hi @talltom , @nashinmahtani is working on it and editing the voiceover. Will keep you updated.
@matthewberryman thanks, I edited that text.

**Comment by ojha-url** [comment]
Added via f28e7e1, review at https://dev.petabencana.id to close issue.

**Comment by prittandrani** [comment]
Hi @ojha-url looks great, thanks. @nashinmahtani will provide the link as soon as she is done.
Quick suggestion for the translation:
- on text under the tab icons:
Map -- Peta
Report -- Laporkan
Info -- Info
- on the Report submenu:
Report with Twitter -- Laporkan lewat Twitter
Report with Telegram -- Laporkan lewat Telegram
Report with local applications -- Laporkan lewat aplikasi lokal
