### ISSUE TITLE
Web menu info/about tab content

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#133]
I currently have the following snippets. Requires a review and translation.

> PetaBencana.id is a project initiated by the Urban Risk Lab at MIT as a free, transparent platform for emergency response and disaster management in megacities in South and Southeast Asia.

> The platform adopts a  “people as sensors” paradigm, where confirmed reports are collected directly from the users at street level in a manner that removes expensive and time-consuming data processing. This framework creates accurate, real-time data which is immediately made available for users and first responders.

> PetaBencana.id gathers, sorts, and visualizs data using specially developed CogniCity Open Source Software - an enterprise-level platform for emergency response and disaster management - to transforms the noise of social and digital media into critical information for residents, communities, and government agencies.

**Comment by prittandrani** [comment]
BI Translation:

PetaBencana.id merupakan sebuah proyek yang diinisiasi oleh Humanitarian Infrastructures Group di MIT yang bertujuan untuk mengembangkan CogniCity Open Source Software (CogniCity OSS) sebagai sebuah platform gratis dan terbuka untuk manajemen kebencanaan di kota-kota besar di Asia Selatan dan Tenggara.

Platform ini menggunakan paradigma "manusia sebagai sensor terbaik", di mana laporan terkonfirmasi dikumpulkan secara langsung dari pengguna di lapangan, dengan metode yang memungkinkan pengolahan data yang cepat dengan biaya minimum. Kerangka kerja ini menghasilkan data real-time dan akurat, yang langsung tersedia untuk pengguna dan petugas darurat berwenang.

PetaBencana.id mengumpulkan, menyortir, dan memvisualisasikan data menggunakan CogniCity Open Source Software - sebuah platform untuk manajemen kebencanaan - untuk mengubah kicauan di media sosial dan digital menjadi informasi penting bagi warga, komunitas, dan instansi pemerintah.

**Comment by prittandrani** [comment]
Hi @ojha-url I saw the info tab already updated on the dev, thanks! :)

I noticed it needs some translation:
- for the blue text:
PetaBencana harnesses the power of social media to gather, sort, and display information about flooding in real time.
PetaBencana memanfaatkan kekuatan media sosial untuk mengumpulkan, menyortir, dan menampilkan informasi banjir secara real-time.
- Partners -- Partner
- Map credits -- Sumber peta

For the partners logo, I think we need to keep it updated as we will have another data source coming in and ensure the cooperation with local agencies. But for now beside the 4 logos would you please add these others with the links?
- Qlue
![lg_qluewithtext](https://cloud.githubusercontent.com/assets/22338984/21955233/33dde408-da99-11e6-92c3-111c2742b4d6.png)
Link: [http://www.qlue.co.id/](url)
- PasangMata detik.com
![png-37-5874b681536890074acbe02ec58c0ae5-pasangmata](https://cloud.githubusercontent.com/assets/22338984/21955318/7e48ee28-da9b-11e6-98e0-ebcb24e0e16c.png)
(You can choose which color is better)
Link: [http://pasangmata.detik.com/](url)
- Z-Alert
![rev2-02](https://cloud.githubusercontent.com/assets/22338984/21955326/a466956a-da9b-11e6-9733-0a68510a27b2.png)
Link: [https://www.zurich.co.id/id-id/kampanye-kami/zurich-alert-the-alert-you-really-need](url)

(Let me know if it's appropriate to send you the logos through this comment, or if I need to send you through emails)

---
Another thing, I think it is also good to explain the privacy (as we did at PetaJakarta.org cc @talltom @anexact ) although we included it in Contribution Agreement. Like this:
We do not store any information about users. Information derived from location-enabled mobile devices is mapped in real-time; this information is available through an open API for additional applications.

Translation:
Kami tidak menyimpan informasi tentang pengguna. Semua informasi yang berasal dari perangkat seluler bergeolokasi dipetakan secara real time; informasi ini dapat dilihat lewat API terbuka untuk aplikasi lain.

**Comment by ojha-url** [comment]
Thanks @prittandrani, the updated content should be live now.

**Comment by prittandrani** [comment]
Hi @ojha-url thanks! Looks like the BNPB logo put on the info is incorrect (the text should say Badan instead of Bandan), would you please change it to this one?
![bnpb logo](https://cloud.githubusercontent.com/assets/22338984/21974172/b7bc4d82-dbf7-11e6-8048-65c7526c7995.png)

Also the text "people as the best sensors" and the "visualizes" don't need to be bold; I formatted it in bold here earlier to highlight the difference. (Sorry if this is too much hassle, just want to make sure that public users are not confused) :)

Thanks for all the hardwork! cc @talltom

**Comment by matthewberryman** [comment]
@ojha-url @talltom @prittandrani I have just fixed this in master and dev and deploying it now.
