### ISSUE TITLE
Maps: OpenStreetMap Credits, Scale, and Legends

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/petabencana.id#136]
Hi all, I noticed that we have not put the OpenStreetMap credits yet on the right corner of the map. I saw this is important as OSM said: "You are free to copy, distribute, transmit and adapt our data, as long as you credit OpenStreetMap and its contributors. If you alter or build upon our data, you may distribute the result only under the same licence. The full legal code explains your rights and responsibilities." (from OSM page).

The credits design & requirements are explained here: [https://www.openstreetmap.org/copyright](url)

I think the scale & legends also required to help people understand the map, although there is only blue water drop signs right now for the reports.

Thanks!
cc @talltom @ojha-url , @fadmastuti @anexact

**Comment by talltom** [comment]
Reference mapbox policy https://www.mapbox.com/help/attribution/

**Comment by talltom** [comment]
Leaving this open as we need to add a Mapbox attribution as per my link above.
