### ISSUE TITLE
Side panel fails to open under some conditions

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/petabencana.id#140]
Hey, I'm noticing a bug in production where the side panel doesn't open when you click the top right icon. 

I notice that his happens when you go directly to a city's map (https://petabencana.id/map/bandung) or when you go to (https://petabencana.id/map/) then select either Bandung or Surubaya and try to click the side pane. 

![screen shot 2017-01-16 at 7 36 57 pm](https://cloud.githubusercontent.com/assets/8716123/21985988/5f4d7582-dc23-11e6-8cd3-4093a58a8999.png)

I have also noticed this behavior when going to https://petabencana.id/ and selecting a city, but then it only sometimes fails, not always. 

Probably something in the context is not being set?

**Comment by matthewberryman** [comment]
The [dev site](https://dev.petabencana.id/) doesn't have the js minified, so if you see the bug there you can get out the actual variable names and line numbers:
```
Uncaught TypeError: Cannot read property 'target' of undefined
    at Map.hidePane (map.js:52)
    at Map.showPane (map.js:65)
    at CallScope.evaluate (vendor-bundle.js:8218)
    at Listener.callSource (vendor-bundle.js:11753)
    at vendor-bundle.js:11777
    at HTMLDocument.handleDelegatedEvent (vendor-bundle.js:9921)
```

I don't have time to look more at this issue today but can take a look tomorrow if it helps.

**Comment by abrahamq** [comment]
Thanks for the tip Matthew! 

I think the error stems from line 65 of map.js. The show pane function calls the hide pane function. Removing this line fixes the issue, but I don't have enough context to tell if I'm breaking something else. Why is showPane() also calling hidePane('#reportPane')?

**Comment by ojha-url** [comment]
Hi Abe, this was required to prevent the side pane from opening on top of the report info pane. It fails because of scope issues in the way layers.js and map.js interact. We have #102 set to streamline this bit and make layers class an aurelia component. It was working until @talltom pushed some changes to fix feature requests by the field team. I will look into this tomorrow.

**Comment by ojha-url** [comment]
Here's a quick fix:

In hidePane(), change this: 
`if (this.layers.selectedReport !== null) {`
to:
`if (!!this.layers.selectedReport) {`

**Comment by abrahamq** [comment]
Awesome, no worries, I just noticed the bug in production and thought I should log an issue. 
Do you want to check in the fix or should I?

**Comment by ojha-url** [comment]
Will do it tomorrow morning. This fix would still cause issues in the case
where the side pane is open and then a user clicks on a report. The
menu/close would be glitching.

**Comment by talltom** [comment]
Just pushed a fix for this to dev. It happens when there are no reports on the map, which is why I didn't catch it in testing (note to self, new test case). Thanks.
