### ISSUE TITLE
Investigate Telegram share button (intent) on reports

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#142]
- share dialogue which opens different options?
- twitter, whatsapp, telegram, facebook

**Comment by ojha-url** [comment]
Android share dialogue verdict: not possible
http://stackoverflow.com/questions/19284726/use-android-share-intent-in-javascript-in-chrome

**Comment by ojha-url** [comment]
Nice repo for reference
https://github.com/bradvin/social-share-urls
