### ISSUE TITLE
Reports modal doesn't open in Firefox

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#144]
Expected behavior: zoom to report and open
Actual behavior: Icon is marked as orange without modal opening.

Firefox v50.1.0 on OSX.

https://petabencana.id/map/jakarta

**Comment by prittandrani** [comment]
Hi @talltom this issue also happened when using the REM with Firefox (tried on Windows 7), with actual behavior: the blue report icon pops up on the screen.

![whatsapp image 2017-01-20 at 15 15 33](https://cloud.githubusercontent.com/assets/22338984/22142746/04bc3388-df2a-11e6-860e-3558b08a841c.jpeg)

**Comment by talltom** [comment]
Notes:
- doesn't happen on Firefox for mobile
- on desktop clicking on a flood report gives:
`RangeError: invalid time zone in DateTimeFormat(): ASIA/JAKARTA`
- this is probably also related to #143

**Comment by talltom** [comment]
Looks like timezone specification isn't well supported across all browsers
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString#Browser_compatibility

- TODO -> manually derive local time with knowledge that Jakarta is UTC+0700
