### ISSUE TITLE
flag errors in user input

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#149]
I noticed when doing some testing that, if I put in 0cm as the flood height, the slider on the last card page is greyed out and inoperative, with no feedback as to what is the problem.

**Comment by ojha-url** [comment]
Nice find!
The check for required inputs returns a false for value 0, hence disabling the swipe. Will change the minimum value in the slider to 1cm.

**Comment by matthewberryman** [comment]
Alternatively we could use the check to report back to the user what the problem is?
@talltom

**Comment by ojha-url** [comment]
Will add that to #123 in that case. Currently looking at another bug, where if user selects lowest value (0cm or 1cm) and navigates back, it resets to default.

**Comment by ojha-url** [comment]
Working fix, moved to #123.
