### ISSUE TITLE
Fix description bug

### ISSUE THREAD

**Issue by MaanasaPriyaa** [urbanriskmap/petabencana.id#15]
Description set in description.js not picked up in parent cards.js but location works fine.

**Comment by abrahamq** [comment]
Fixed, the issue was with the scope of the this keyword in the getter text() method. I am actually still a little unsure of how exactly the this keyword in js works/ why it's different in the getter method? What the heck js.

**Comment by abrahamq** [comment]
Actually, this is still broken. I fixed it in the worst way possible by using static variables in the Description class? I think? I'm very very confused about how the parent (Cards.js) is supposed to communicate and get the text that is entered into the Description object. Also confused as to what referring to Description.variableName does inside of the Description class- am I correct in thinking that this creates static variables. @mgvarley could you provide guidance/ a possible solution for this? I saw someone else using message passing through the Event Aggregator to make this work, but that seems like a lot of boilerplate and overhead just to do this? 

To be completely clear: there's several cards: Location, Depth, Photo, and Description. The route/cards/description/Description.js model needs to grab the text from the textarea and make it available to the route/cards/card/Card.js model somehow. I think that the current dependency injection is actually just injecting the description model statically and not dynamically?

**Comment by mgvarley** [comment]
Hi Abe - I haven’t done much with this in aurelia yet but it is supposed to be one of the strengths of this kind of framework, have a look at http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-basics/1
 which walks you through data binding concepts and http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components/1
 which describes how to create and consume reusable components.  It helps to think of your app in terms of its state - your goal is to manipulate that state through javascript and then the view is just a skin on top of it - it took me a while to get to grips with this when I first started creating single page apps - I use React for my own projects but I imagine aurelia shares a similar ethos.  From what you describe here it sounds like there is the concept of a Card which will hold the state and then components: Location, Depth, Photo and Description which provide specific functionality to work on each aspect of the state, is that correct?  I would imagine there is coverage in the docs or a tutorial online for aurelia which will cover off these kinds of parent/child relationships.  If I get chance this evening I will take a look as well.


Mark




>

**Comment by abrahamq** [comment]
This has been fixed by using message passing through Event Aggregator. This gives us the ability to gather events from loosely coupled components and should be pretty scalable.
