### ISSUE TITLE
New additions to locales, pending translation

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#156]
Hi @fadmastuti, @anexact, 
The following error messages need to be translated, i'll update the code as soon as this is completed before @talltom deploys to petabencana.id, thanks.

**KEY:  Value**
_Translate 'Values' only_
                  
**_Error notification headers_**
"location_1": "GPS location error",
"location_2": "Unsupported city",
"photo_1": "Size limit exceeded",
"photo_2": "Unsupported browser"
_**Error notification messages**_
"location_1": "Drag map to pick a location",
"location_2": "Supported cities: Jakarta, Surabaya & Bandung.<br>Reports marked outside these cities will not appear on the map.",
"photo_1": "Selected photo exceeds size limit of 4.2mb",
"photo_2": "Photo upload is not supported by your browser"
"location_check": "Unsupported location, report will not appear on map"

**Comment by fadmastuti** [comment]
Hi @ojha-url ,

Translation:

**_Error notification headers_**
"location_1": "lokasi GPS bermasalah",
"location_2": "Kota belum terjangkau",
"photo_1": "Ukuran terlalu besar",
"photo_2": "Browser tidak mendukung"

**_Error notification messages_**
"location_1": "Drag peta untuk memilih lokasi",
"location_2": "Cakupan wilayah: Jakarta, Surabaya, Bandung.
Laporan dari luar area ini tidak dapat ditampilkan pada peta.",
"photo_1": "Foto yang dipilih melebihi kapasitas 4.2mb",
"photo_2": "Foto yang dipilih tidak didukung oleh browser"
"location_check": "Lokasi tidak terbaca, laporan tidak dapat ditampilkan di peta"
