### ISSUE TITLE
Cards can't take a new image

### ISSUE THREAD

**Issue by fadmastuti** [urbanriskmap/petabencana.id#157]
Both iphone and android lose the ability of taking a new photo from card's option either from twitter or telegram.

**iphone (telegram)**

![iphone image blank take a new photo](https://cloud.githubusercontent.com/assets/2441950/22368651/529de872-e4ba-11e6-9af2-9c6dfbce584b.jpeg)

*only a blank image appears

**android (twitter and telegram)**

![android image photo option](https://cloud.githubusercontent.com/assets/2441950/22368684/7d111656-e4ba-11e6-9525-3d78947cf570.jpeg)

cc @talltom @anexact

**Comment by talltom** [comment]
@fadmastuti - I cannot recreate this. Working fine on my device. Please can you add:
1) phone operating system version
2) default browser version (E.g. safari or chrome)

Thanks

**Comment by matthewberryman** [comment]
I can recreate in telegram and tweetbot in app browsers on iOS. [This](https://discussions.apple.com/thread/6791197?start=0&tstart=0) suggests it's a privacy issue, though in tweetbot I had to take a picture through the main UI to get it to prompt me to enable camera, and then it still didn't work with the in app browser—perhaps a bug with iOS then. Telegram doesn't support image sending in the app itself, so there's no way to get this on.

**Comment by talltom** [comment]
Hi @matthewberryman thanks for helping out on this one.

I tested this on a physical iPhone and could not recreate. In the lab on Monday I will try and disable the privacy settings that you link too and see if I can recreate, should help us narrow it down.

Is there a way we can ask Safari users to check privacy settings? So we could build a responsive UI?

Ping @fadmastuti and @anexact so you're aware that this will most likely be an issue through Monday's presentation until we can understand that issue more.

**Comment by matthewberryman** [comment]
I've tried this on 10.2.x and 10.3 (beta). 
@talltom I believe it's the per app privacy settings, not Safari settings, that need to be changed. Also applies to location (though in that case at least users can swipe to adjust location) and camera separately.

**Comment by talltom** [comment]
As this is an issue with app privacy settings we can't make any changes.
