### ISSUE TITLE
Qlue link on How to Report Tab

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/petabencana.id#159]
Hi! As @matthewberryman found out that Qlue just launched the iOS version today, here are the link that we can put on the How to Report Tab:

Qlue for Android [https://play.google.com/store/apps/details?id=org.qluein.android](url)
Qlue for iOS [https://itunes.apple.com/us/app/qlue-jakarta-smart-city/id987432944?ls=1&mt=8](url)

my suggestion is I think it is okay if we cannot do the user-agent based link, we can put both of them like this:
"Qlue: for Android | for iOS" (in BI: "Qlue: untuk Android | untuk iOS")
or
"Qlue for Android | Qlue for iOS" (in BI: "Qlue untuk Android | Qlue untuk iOS")
or just erase the word for:
"Qlue: Android | iOS"

whichever looks better on the page. What do you think? :)

**Comment by ojha-url** [comment]
![2017-02-03 17 15 56](https://cloud.githubusercontent.com/assets/22597094/22600938/c685ed52-ea0a-11e6-9414-3413c1581716.png)

**Comment by prittandrani** [comment]
Thanks @ojha-url !
