### ISSUE TITLE
Query by date

### ISSUE THREAD

**Issue by firmanhadi** [urbanriskmap/petabencana.id#166]
Hi all,

Thank you for your great contribution.
I am working at Geoinformatics Center, Asian Institute of Technology.
Mostly we work with satellite imageries for disaster response.
Your data will be a valuable input for us to validate our results 
(e.g., flood extent).
It will be good if we can query the data by date. Currently, we don't find
time information in the data.

Thanks.

Firman.

**Comment by matthewberryman** [comment]
Hi Firman,

I gather you are most interested in the flood-affected polygon information? This is available under our /floods API as documented at https://docs.petabencana.id/

Flood affected areas polygons come directly from BPBD DKI Jakarta. The are created on a combination of the resident reports from PetaBencana.id and on-the-ground human intelligence collected by BPBD and collated by the staff in the control room. The designation of a flooded area is not automated (albeit computer assisted) RW regions are marked as flooded, including estimated water depth, normally phoned-in by Kelurahan (village) etc., by BPBD staff. There are time stamps that indicate when the flood affected area was first demarcated as such by BPBD. Flood affected areas are removed from the map as BPBD staff receive the all clear. I.e. if an area is marked as flooded on the map, this is a good indicator that it is currently affected by flood. There's at present no aggregation/averaging of this data, though I am working on some APIs that do this.

We do keep historical data on flooded regions as well as the social media reports, and @talltom is best placed to advise on potential access to this for research collaborations.

Regards,
Matthew.


On 23 Feb 2017, at 17:27, Firman Hadi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all,

Thank you for your great contribution.
I am working at Geoinformatics Center, Asian Institute of Technology.
Mostly we work with satellite imageries for disaster response.
Your data will be a valuable input for us to validate our results
(e.g., flood extent).
It will be good if we can query the data by date. Currently, we don't find
time information in the data.

Thanks.

Firman.

**Comment by firmanhadi** [comment]
Hi Matthew,

Thank you very much for the response.
I have read the docs before, that's why I requested if we can query by date, it will be awesome :D.
Thanks also for forwarding this to Tomas.

Cheers,

Firman.

**Comment by talltom** [comment]
Hi @firmanhadi,

Just to confirm that we've added a new `timeperiod` parameter to the reports API (for individual reports from residents) where you can search back up to a week. See here: https://docs.petabencana.id/routes/reports.html

Unfortunately, due to server constrains we can't open the entire archive during the monsoon season, however we will be releasing the data after the monsoon for analysis.

If you want to discuss how we might collaborate on this drop me a line tomash@mit.edu

Thanks,

Tomas

**Comment by firmanhadi** [comment]
Hi Tomas,

Thank you very much for adding new parameter.
Although currently restricted to the last 7 days,
it will be very useful for our research.

I hope we can collaborate more in the future.

Best regards,

Dr. Firman Hadi | Research Specialist | firmanhadi@ait.asia <mailto:firmanhadi@ait.asia> 
Geoinformatics Center – Asian Institute of Technology                             
P.O. Box 4 | Klong Luang, Pathumthani 12120 | Thailand                             
T: +66 2 524 6489 | M: +66 9 4353 3911 | F: +66 2 524 6147
W: geoinfo.ait.ac.th <http://geoinfo.ait.ac.th/>
