### ISSUE TITLE
Check node version in Travis

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#173]
@matthewberryman - our Travis build spec is using node js "4.4.5".

This seems out of date, I just want to check what our build system (Jenkins) is actually using to run Aurelia prior to push to S3. Are you good to check this? Thanks.

**Comment by matthewberryman** [comment]
Currently v6.9.2 but I plan on updating that to the latest v6.x.x soon.

**Comment by talltom** [comment]
OK @matthewberryman  I updated node in Travis per your comment above (see 8dc967815dddbf75da1471dc191c518c74f677e3). Please remember to update when you update build environment, or feel free to reopen this if need.

**Comment by matthewberryman** [comment]
@talltom thanks for closing, not sure why github didn't automatically close on use of 'fixes' keyword (perhaps because it had been re-opened)
