### ISSUE TITLE
Flood area info translations

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#178]
Pending translations... thanks!

        "title": "Flood affected area",
        "level_hint": "Alert level",
        "time_hint": "Last updated",

            "severity": "Unknown",
            "description": "An unknown level of flooding, use caution"

            "severity": "Minor",
            "description": "Flooding between 10 to 70 cm"

            "severity": "Moderate",
            "description": "Flooding between 71 to 150 cm"

            "severity": "Severe",
            "description": "Flooding over 150 cm"

**Comment by prittandrani** [comment]
"title": "Area terdampak banjir"
"level_hint": "Status ketinggian banjir"
"time_hint": "Diperbarui pada"

Unknown -- Tidak diketahui
An unknown level of flooding, use caution -- Ketinggian banjir tidak diketahui, harap berhati-hati

Minor -- Rendah
Flooding between 10 to 70 cm -- Banjir antara 10 sampai 70 cm

Moderate -- Sedang
Flooding between 71 to 150 cm -- Banjir antara 71 sampai 150 cm

Severe -- Parah
Flooding over 150 cm -- Banjir di atas 150 cm

**Comment by ojha-url** [comment]
Thanks @prittandrani !
