### ISSUE TITLE
blank page in chrome

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#181]
```
vendor-bundle.js:1 Unhandled rejection ReferenceError: _dec is not defined
    at Object.<anonymous> (https://petabencana.id/scripts/vendor-bundle.js:13:18153)
    at Object.execCb (https://petabencana.id/scripts/vendor-bundle.js:3:6591)
    at b.check (https://petabencana.id/scripts/vendor-bundle.js:3:303)
    at b.enable (https://petabencana.id/scripts/vendor-bundle.js:3:3089)
    at Object.enable (https://petabencana.id/scripts/vendor-bundle.js:3:5648)
    at b.<anonymous> (https://petabencana.id/scripts/vendor-bundle.js:3:2946)
    at https://petabencana.id/scripts/vendor-bundle.js:2:26473
    at each (https://petabencana.id/scripts/vendor-bundle.js:2:25948)
    at b.enable (https://petabencana.id/scripts/vendor-bundle.js:3:2446)
    at Object.enable (https://petabencana.id/scripts/vendor-bundle.js:3:5648)
    at b.<anonymous> (https://petabencana.id/scripts/vendor-bundle.js:3:2946)
    at https://petabencana.id/scripts/vendor-bundle.js:2:26473
    at each (https://petabencana.id/scripts/vendor-bundle.js:2:25948)
    at b.enable (https://petabencana.id/scripts/vendor-bundle.js:3:2446)
    at b.init (https://petabencana.id/scripts/vendor-bundle.js:2:31397)
    at https://petabencana.id/scripts/vendor-bundle.js:3:4964****
```

@talltom it's possible this is a cache catchup issue. I will try a few things first and confirm

**Comment by matthewberryman** [comment]
Nope, this is not a CF cache issue, as I see it on the underlying s3 bucket too. I am manually rolling back now. Suspect it's because of a difference between your aurelia environments as I saw a similar bug before. Please test using npm run build and open static files. I can take a look this arvo my time.

**Comment by talltom** [comment]
Ok thanks Matthew. Please confirm when rolled back. 

cc @ojha-url and @abrahamq

**Comment by talltom** [comment]
Accessing "http://localhost:8080/map/jakarta" on a prod build gives:
`[Mon Mar 06 2017 18:18:56 GMT-0500 (EST)] "GET /map/jakarta" Error (404): "Not found"`

**Comment by matthewberryman** [comment]
@talltom the prod build doesn't stand up a server by default and also the default port in aurelia_projects/environments/local.js is 9000

**Comment by talltom** [comment]
@matthewberryman I agree. I'm testing my build using http-server on production build items to try and recreate S3 conditions.

I can't recreate your issue above after building locally.

**Comment by matthewberryman** [comment]
@talltom I'm just about to switch jenkins to put build (instead of build-dev) on dev.petabencana.id for testing, although I think I have identified the bug. Cache invalidation still happening, most users should be fine on prod site now.

**Comment by talltom** [comment]
Ok great. Thanks. Gotta grab some 🍛 <food> this end!

**Comment by talltom** [comment]
I have a working theory that this is a dependency issue. With a fresh clone of the repo I am no longer able to build older working prod versions anymore (I went back 19 days: a993641cbbbcb6d4c553ac8a414198a95894927e). I can however build working prod versions from my useful working directory, suggesting something's changed in an external library. This needs confirming on a second machine before we continue on this line...

**Comment by talltom** [comment]
also bringing @abrahamq in to help us test; if my above hunch is correct development's stuck until we can fix this one.

**Comment by matthewberryman** [comment]
I just reverted the attempts at fixing I made earlier, as they didn't fix things, and I want to revert to a point where build-dev was building correctly (assuming no dependency updates as the cause). I will swap back jenkins dev to build-dev.

**Comment by matthewberryman** [comment]
@ojha-url isolated this to the minification and in particular the uglify-js version used. Looking at the uglify release history it seems be quite a fast moving project (particularly as they work on uglify-harmony for ES6), so I suggested to @ojha-url that we use ~ instead of ^ for uglify in package.json, so we're not forced forwards on minor releases. He's tested 7707a15 locally, and I (with a temporary reversion to `npm run build` in jenkins dev) have now tested on AWS, so unless there's major rainfall overnight (nothing significant on forecast), I will start deploying early tomorrow (WIB). I will drop TTL on CF cache now in preparation for rapid testing, which is fine as we're not seeing heavy traffic.

To catch these issues more easily in future, I will set up staging.petabencana.id later tonight (AEDT) that has dev branch but `npm run build` as the build process.

**Comment by matthewberryman** [comment]
Ok staging.petabencana.id is now set up (from my perspective, but CF and DNS will take up to half an hour from now to propagate). 
New workflow for @talltom and myself is to also check [staging.petabencana.id](https://staging.petabencana.id) after checking dev.petabencana.id but before merging to master, to catch these sorts of errors that result from aurelia build/minification/map differences between `npm run build-dev` and `npm run build`.
