### ISSUE TITLE
No error handling if POST to /cards/{{cardId}}/images fails

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#186]
https://github.com/urbanriskmap/petabencana.id/blob/master/src/routes/cards/cards.js#L141

**Comment by matthewberryman** [comment]
cc @talltom

**Comment by talltom** [comment]
@ojha-url should we pass a message to the user if the image upload fails. Technically we are handling the error (the card flow doesn't break) but we're not updating the UI to reflect problems with the image.

**Comment by talltom** [comment]
Moved this over to https://github.com/urbanriskmap/cognicity-cards/issues/4
