### ISSUE TITLE
supply / make a hard link for privacy

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#187]
Facebook want a URL that will open the privacy policy directly.
At the moment I need to go to https://petabencana.id/ , select a city, open the info page, and swap language to en (they will want to see en version).
Can we please make this available on a custom URL.

**Comment by talltom** [comment]
@matthewberryman - FYI. also waiting on a translation of an updated privacy policy, should have it next week.

**Comment by matthewberryman** [comment]
@talltom ok thanks

**Comment by MaanasaPriyaa** [comment]
@matthewberryman working on getting the privacy url done. I will have it ready soon

**Comment by MaanasaPriyaa** [comment]
@matthewberryman I mean custom URL.

**Comment by talltom** [comment]
@all - I have updated policy documents in both English and Indonesian. Task on me to update in the JS files.

@MaanasaPriyaa - what branch are you working on for this?

**Comment by talltom** [comment]
Update on status:
- site URL now supports optional parameters for language and side-bar tab, so that the tab is open when the map page is loaded
- the cards have been updated to include both the privacy policy and user agreement

Outstanding:
- show privacy policy and user agreement on map page.

**Comment by ojha-url** [comment]
@matthewberryman, @talltom, please check dev site before i add a pull request into master.

https://dev.petabencana.id/map?lang=en&tab=info can be used as the permalink for user agreement/privacy purposes. The process involves one more step - scrolling down & clicking on the link towards the bottom in info panel.

**Comment by matthewberryman** [comment]
Not working for me, because @abrahamq has made commits to the e2etesting branch, and that is getting deployed to dev so we can test that. @ojha-url you will need to wait until @abrahamq has finished with #194 or perhaps consider merging your work into his branch, although I'd rather keep it cleaner unless we're in a rush to get FB messenger in production. cc @talltom

**Comment by talltom** [comment]
@abrahamq - ETA on pull request for the e2etesting branch? I'm available today to review.

**Comment by matthewberryman** [comment]
Ok I've git the e2eTesting branch deployed to a different host now (will follow up with details on gitter), and now I can test this, and I think it looks mostly good from a UX point of view—I think we need to put the link to User Agreement & Privacy Policy near the top so it's obvious to anyone (inlc. Facebook reviewers). I will leave the legalese to @talltom

**Comment by talltom** [comment]
OK, thanks @matthewberryman

**Comment by matthewberryman** [comment]
@talltom How are we tracking on this? Are we going to provide a link direct to privacy policy, or at least as I suggested move it up the page? @MaanasaPriyaa

**Comment by talltom** [comment]
@matthewberryman We now have routing option https://petabencana.id/?lang=en&tab=info which opens the side panel in English and the link to privacy is prominently displayed. 

Do you think this meets requirements?

**Comment by matthewberryman** [comment]
@talltom I disagree that it's prominently displayed, I have to scroll down on desktop, tablet, and mobile phone before I can see there's a privacy (JS, not hard) link, which is why I asked that it be moved up the page; or better yet can we not supply a hard link to just the privacy information?

**Comment by talltom** [comment]
This has been addressed in 240d48e48e99240c76bd17aaaa3907613754e586
and documentation added to README in ff08cf6b4db7173fb2dcca37360b9c973ec1abc2
