### ISSUE TITLE
reference to src files

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#195]
https://github.com/urbanriskmap/petabencana.id/blob/chennaiChanges/src/routes/cards/cards.js#L44
https://github.com/urbanriskmap/petabencana.id/blob/chennaiChanges/src/routes/cards/cards.js#L49
refer to files under src/ but src/ isn't deployed because it's source. 
Instead these I will move under a subdirectory of assets.

**Comment by matthewberryman** [comment]
@abrahamq @MaanasaPriyaa I think this is the problem why we're not getting cards loading in dev but are on localhost.

**Comment by matthewberryman** [comment]
Fixed in https://github.com/urbanriskmap/petabencana.id/commit/930d7f1926ab444f240622b000070318a38da434

**Comment by abrahamq** [comment]
How can we make our Dev environment closer to Prod? I looked at some of
http-server documentation and some other simple http servers but couldn't
find anything about making the error handling look like AWS. There's
Aurelia-node, which uses node and express to serve bundled files? Should we
look down this path?
