### ISSUE TITLE
"pengguna" text in terms/pricacy window breaks on small screens

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#200]
![screen shot 2017-05-24 at 4 06 59 pm](https://cloud.githubusercontent.com/assets/944642/26423288/15074836-409b-11e7-992b-b90954b54907.png)

**Comment by abrahamq** [comment]
Fixed in commit https://github.com/urbanriskmap/petabencana.id/commit/5125f129f3603de8f78eed5e3796dd061b7c9fd3
