### ISSUE TITLE
City to City Navigation 

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/petabencana.id#211]
FY17Ext Dev Meeting Field Office 02 _ Request to move city to city navigation to map itself, not in nav panel; thus, when zoomed out, it is clear to user that they can drill down into another city bounding box

**Comment by talltom** [comment]
@anexact - This breaks the paradigm of the map, which is essentially served as three separate maps for three different cities, which also controls the loading of different data. Whilst technically possible map based navigation could lead to the very confusing situation of looking at Bandung, with only data for Jakarta showing (if the user zooms out and pans). This is why panning the map is currently fixed, as discussed at the beginning of PetaBencana. I think we're going to have to stick with this for the time being, as we're pushing the limits of what our routing engine can do behind the scenes.
