### ISSUE TITLE
Request icon change for main page menu button 

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/petabencana.id#216]
FY17Ext Dev Meeting Field Office 07 _ request to standardize the menu button as a "hamburger" icon to make locating the menu easier for users

**Comment by talltom** [comment]
Is there feedback from users on this? We've changed this button logo lots of time. @ojha-url suggests a small group of user testers in Indonesian so see how they feel about the add report button. We would loose the immediacy of the "add report" icon.

**Comment by talltom** [comment]
After further discussion, the proposal is to switch to the hamburger for now, and think about how to drive users to "add reports".

**Comment by asbarve** [comment]
Resolved in the new version with Hamburger menu + add menu button and deep links
