### ISSUE TITLE
Implement Translation piece

### ISSUE THREAD

**Issue by MaanasaPriyaa** [urbanriskmap/petabencana.id#22]
1.https://github.com/aurelia/i18n

Will update with more details as I find them.

**Comment by ojha-url** [comment]
Custom attributes to view templates;
and check for string declarations in view models.

**Comment by ojha-url** [comment]
Completed, few elements in cards require attributes and strings in each translation.json.
Pending decision of allowing user to switch language, and its code to do so on-the-fly.

**Comment by mgvarley** [comment]
Switching language should be relatively straightforward.  You will need a language control in the menu bar which is bound to the il8n.setLocale - more information here https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md
.  Happy to help with this if you need me to.
