### ISSUE TITLE
Request to fix spelling errors in REM Report Table

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/petabencana.id#220]
FY17Ext Dev Meeting Field Office 11 _ request to fix bug in REM Report Table spelling errors _ MF to send screenshot and correction

**Comment by prittandrani** [comment]
_ after clicking the reports table icon, in pop-up Report column below, “Laporkan” should be “Laporan”
![image](https://user-images.githubusercontent.com/22338984/29503321-d4bb2e44-8660-11e7-98f5-63d39883e577.png)

_ in report detail popup (after clicking report description on table above), “Banjir Laporkan” should be “Laporan Banjir”
![image](https://user-images.githubusercontent.com/22338984/29503336-04d4b65e-8661-11e7-8d12-fe30b22cbc29.png)

**Comment by matthewberryman** [comment]
Filed in wrong repo, have opened issue in correct repo.
