### ISSUE TITLE
Request for bug fix on REM / Public map report time stamps

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/petabencana.id#221]
FY17Ext Dev Meeting Field Office 12 _ request to correct bug that shows a 7 hour difference between the real report time and its display in the REM.

**Comment by prittandrani** [comment]
_ on reports table (as shown below) the time shown is different with the actual report (7-hour difference)
![image](https://user-images.githubusercontent.com/22338984/29503359-3bb1234c-8661-11e7-83c8-b2485374b656.png)

However, the time is correct in the report details popup table (after clicking single report on the reports table) as shown below
![image](https://user-images.githubusercontent.com/22338984/29503373-5d899a94-8661-11e7-9ce6-8b65dd6ef765.png)

**Comment by talltom** [comment]
- note to self. Port the new time zone function from petabencana to REM table.

**Comment by talltom** [comment]
- This bug should be moved to rem repo.

**Comment by talltom** [comment]
This was fixed in a13bdc04ea83540c842aae4ffda4773be4c0d382
- reports table was not using the `formatTime` function required to put times into ICT.
