### ISSUE TITLE
New default zoom level (riskmap us) breaks petabencana

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#235]
Expect to see Java, but instead zoomed into middle.

![screen shot 2017-09-25 at 1 44 53 pm](https://user-images.githubusercontent.com/944642/30822758-e0bdfde0-a1f7-11e7-85ab-adf5b2f11fc9.png)

**Comment by talltom** [comment]
- currently occurs on dev only.

**Comment by asbarve** [comment]
Resolved - zoom levels changed for Broward - all three instances share same disastermap.js parameters.

**Comment by talltom** [comment]
But now I can see Miami again? Shouldn't we have different zoom level for different instances? We have locale center points (lat/lng) can't we add zoom level there as well?

**Comment by asbarve** [comment]
Added deployment specific start and min-zoom parameters
