### ISSUE TITLE
Bugs on Twitter reply for Indonesian language

### ISSUE THREAD

**Issue by emirhartato** [urbanriskmap/petabencana.id#238]
Kudos to @prittandrani for discovering this issue. 

# Problems
- When users tweet using Indonesian words "banjir", the reply is in English. However, the GIF is in Bahasa Indonesia. 

![img_0766](https://user-images.githubusercontent.com/1563226/30895943-c679011a-a377-11e7-8198-4a4f5c2601d9.JPG)

- Similarly, when users mention PetaBencana and tweet "banjir", the reply is also in English. However, the card UI is in Bahasa Indonesia. 

![img_0770](https://user-images.githubusercontent.com/1563226/30896015-3ee28978-a378-11e7-8d81-7ac3475eff53.PNG)

![img_0769](https://user-images.githubusercontent.com/1563226/30896032-53ff9b48-a378-11e7-923a-a342ecbe28fb.PNG)

# How to replicate this issue
Simply tweet "banjir" and/or mention PetaBencana 

# Proposed Solution
I thought this must be related to Twitter default language setting. However, changing the default language setting on Twitter doesn't help. The issue remains. So another solution is required.

# Expected outcome
Any "banjir" tweets should have Indonesian replies/responds.

**Comment by talltom** [comment]
Thanks @emirhartato + @prittandrani. We've moved our cards code over to a new cognicity-cards repository (petabencana.id is now just for the map). So I've moved this issue over to that repository and will close this one: https://github.com/urbanriskmap/cognicity-cards/issues/13

Cheers.
