### ISSUE TITLE
Begin fetching from cognicity-server

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/petabencana.id#25]
This involves using aurelia's fetch client to get/put to the server in order to: 

submit and render reports

**Comment by abrahamq** [comment]
Need to have a much more concrete idea of what the api looks like and what it returns in order to be able to do this. I've looked at: https://github.com/urbanriskmap/urbanriskmap-meta/wiki/CogniCity-v3.0-Server-Endpoints-&-Site-Map and I've mapped the endpoints into a folder structure that the [mock server canned ](https://github.com/sideshowcoder/canned) will understand, but I don't have a good idea of what kind of json objects these routes should be giving. Do we have that anywhere @talltom?

**Comment by mgvarley** [comment]
Hi Abe - I am going to be documenting all of this over the next few days in the new gitbook API docs (these will be at https://www.gitbook.com/book/urbanriskmap/cognicity-data-api-docs)


In the meantime the default output format for geographic data is topojson, if you are not familiar with this you can learn more here: https://github.com/topojson/topojson-specification



The endpoints I sent you earlier will also return topojson.  Matthew has these up and running on AWS at:


https://data.petabencana.id/infrastructure/floodgates


https://data.petabencana.id/infrastructure/pumps


https://data.petabencana.id/infrastructure/waterways




etc.  For testing APIs I strongly recommend Postman, it can be downloaded for free here getpostman.com.  It allows you to inspect request and response headers, build authentication tokens etc.  You can also save results to bundles and run automated tests.


m

**Comment by abrahamq** [comment]
Awesome, I'll use that data as placeholders for now. Thanks!

**Comment by MaanasaPriyaa** [comment]
@mgvarley Hi Mark! What is the best practice to share/persist data across view-models in aurelia? I see that singleton instances are one way to go. Any suggestions?

**Comment by talltom** [comment]
Hi at @MaanasaPriyaa let's move this discussion to Gitter as this question isn't directly related to the issue.

**Comment by talltom** [comment]
Hi @abrahamq I've added myself to the assigned list for this as I've got a front end data module to fetch data for the map in the works.

**Comment by MaanasaPriyaa** [comment]
Agreed. My bad.

**Comment by talltom** [comment]
- topojson support is in Aurelia: 1d6bc3dab9ffebff9f409a232aff0da402f5f9b5

**Comment by talltom** [comment]
Fetching reports from data.petabencana.id was implemented in 6c012c6004c062d3695dff4be2cdae6f256314b9
