### ISSUE TITLE
Use travis CI

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#38]
Use Travis CI (including build status in final README.md). Need to resolve issues in #34 and #35 first.

**Comment by talltom** [comment]
TravisCI now executes an Aurelia build, with tests to follow:

https://travis-ci.org/urbanriskmap/petabencana.id/builds/180415049

#34 will be fixed down the track, in the meantime .travis.yml does `cd petabencana-aurelia`

**Comment by talltom** [comment]
Travis badge added to README in b2f6d4edb41a2c992b6da2c87028f2191695b47e
