### ISSUE TITLE
QLUE API and documentation

### ISSUE THREAD

**Issue by fadmastuti** [urbanriskmap/petabencana.id#42]
### API

`http://services.qlue.id/external/petabencana/qlue_marker.php`

#### Parameter

q(required) = jabodetabek or bandung or surabaya
> jabodetabek max 2 days behind
> bandung and surabaya max 30 days behind

#### Example
`http://services.qlue.id/external/petabencana/qlue_marker.php?q=bandung`

#### Result

![image](https://cloud.githubusercontent.com/assets/2441950/20697772/6c2e7668-b62e-11e6-9d25-222b698987e6.png)

cc @talltom @anexact

**Comment by matthewberryman** [comment]
@fadmastuti is this just for flooding data?

@talltom @mgvarley Images are also available over https, we should re-write http to https before storing in the database, as we've done previously. The same is true of videos in their storage bucket, e.g. https://qlueinvideos.storage.googleapis.com/5812e4c456c98.mp4

**Comment by fadmastuti** [comment]
@matthewberryman yes. it is for flooding only (right now). They are happy to open the API for other hazards and cities also in the future when we need it.

**Comment by talltom** [comment]
@matthewberryman - as the city query is required, looks like we'd need
three instances of CogniCity Reports Qlue to get all three streams. I had
hoped we'd just get the whole stream and do our own spatial filtering as
with tweets.

Unless you can see another option?

Dr Tomas Holderness
Research Scientist
MIT Urban Risk Lab

**Comment by talltom** [comment]
An update on this: Reports are now being pulled into the database via https://github.com/urbanriskmap/cognicity-lambda-qlue

These are visible on the map through the reports endpoint. Separately I will open an enhancement request to support videos. But this is longer term because of the infrastructure on the front- end required to support.
