### ISSUE TITLE
Base Map Styling

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/petabencana.id#48]
Review and finalize basemap

https://api.mapbox.com/styles/v1/asbarve/ciw9uids300302pw14f5mapkg.html?fresh=true&title=true&access_token=pk.eyJ1IjoiYXNiYXJ2ZSIsImEiOiI4c2ZpNzhVIn0.A1lSinnWsqr7oCUo0UMT7w#2.01/7.17/38.37

**Comment by ojha-url** [comment]
Not working.
Perhaps conflict with bounds?

**Comment by asbarve** [comment]
https://api.mapbox.com/styles/v1/asbarve/ciw9uids300302pw14f5mapkg/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiYXNiYXJ2ZSIsImEiOiI4c2ZpNzhVIn0.A1lSinnWsqr7oCUo0UMT7w

this is the right link - above is for preview
