### ISSUE TITLE
Validation of Card ID server-side and passed to client

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#56]

**Comment by talltom** [comment]
Port from cognicity-grasp?

**Comment by talltom** [comment]
https://github.com/urbanriskmap/petabencana.id/blob/master/petabencana-aurelia/src/routes/cards/cards.js#L32

**Comment by ojha-url** [comment]
Closed via 6becc642f13b8ac1847534e5c7c7f203482464d9
