### ISSUE TITLE
Handle map & card error cases

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#57]
Map
===
- ~~~typed in a city which doesn't exist~~~ see: 3592cd14043e4fe1c1f0f881249f6e75e1230840
- ~~~report query (by ID) does not exist~~~
- ~~~generic http errors for layers (i.e. internal server error)~~~ see: 32987b4fb5de34bdd76ea53c69e468b5408c8ab1
- ~~Error 404 for random pages~~

Cards
====
- ~~Wrong/incorrect OTL link~~
- ~~Error on submission of completed card (i.e. at server end)~~

**Comment by talltom** [comment]
- Added console.log of errors when fetching or loading map layers
- Use https://notifyjs.com/

**Comment by talltom** [comment]
@ojha-url - not pretty but i added some examples of how to issue notifications in map.js and layers.js

**Comment by talltom** [comment]
Currently, we're redirecting unknown routes to the map. This works locally, but not on prod.

Longer term we need to better understand how to catch errors listed in #65 in Aurelia routing and redirect to an error page.

**Comment by matthewberryman** [comment]
I could get cloudfront to redirect 404s to the map, however that would break the way I've got things set up for https://github.com/urbanriskmap/petabencana.id/issues/71

**Comment by talltom** [comment]
Hi @matthewberryman - yes we had that locally, but I think the redirects are confusing. I propose we aim for 404 pages, with a link <a>"Return to Map"</a>. I'll try and sync with @mgvarley on this today.

**Comment by ojha-url** [comment]
@talltom, this got overwritten by some recent commit, i guess changes made to promise resolutions. 
Now there is no notification in case i enter an invalid report_id. Will look into it.
