### ISSUE TITLE
Check for requisite user inputs

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#6]
Identify mandatory & optional user inputs, disable swipe-to-submit if requisite inputs are not provided.

_Minimum information required for a valid report:_
Location (geolocation; or if not found, check manual entry using map.move?)
Height
Either of Description, Photograph

**Comment by ojha-url** [comment]
There can be 2 alternative i can think of for this:
1. Next button on each mandatory input card remains disabled until user provides input
2. Next button is always enabled, only the 'review & submit' card has a message asking user to 'Go Back' and provide necessary inputs. The swipe-to-submit button remains disabled till all requisite inputs are provided.
@talltom ?

**Comment by matthewberryman** [comment]
I don't think our UI choices should be specific to different input types, so I would avoid things like swiping that don't work on laptop/desktop and avoid things like right click that don't work on touch screens.

**Comment by talltom** [comment]
Hi @matthewberryman thanks for that point - luckily @ojha-url et al have designed a "swipe across" button that works well on touch and non-touch devices (as long as "mouse" type interaction available) as a method of preventing the user accidentally submitting a report.

See page 12 of the design guide for a screenshot: https://github.com/urbanriskmap/userdesign/blob/master/161123_StyleGuide_AB.pdf

**Comment by talltom** [comment]
@ojha-url My proposal is:

Mandatory (via disabled next button):
- location
- flood height

Optional (i.e. next button enabled):
- photo
- text description

**Comment by matthewberryman** [comment]
Ok (sorry I would have tested the code but I'm super busy today).

**Comment by talltom** [comment]
@matthewberryman, no worries. I believe it is nearly (but not quite) ready for testing ;-)

We'll keep you posted.
