### ISSUE TITLE
Show user location on map?

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#60]

**Comment by talltom** [comment]
- have a button below the zoom controls which is always shown
- onclick:
    - check if user in one of target cities:
    - if so, zoom to location & add pin
- if location not found or user not in target city show appropriate error message

**Comment by talltom** [comment]
@ojha-url - filter user location to be in one of the target cities.

**Comment by ojha-url** [comment]
Map content and browser url to display same information in all cases, including geolocation movement (if in supported city)
