### ISSUE TITLE
Translation error on old browsers & iOS

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#62]

**Comment by talltom** [comment]
Unknowns:
1. On old browser no translated text is shown regardless of language (e.g. cards.js)
2. Can we change translation on the fly

**Comment by talltom** [comment]
Occurs on old browsers (which?) and Safari/iOS devices.

**Comment by talltom** [comment]
***Not working*** (dev.petabencana.id does not load)
- Safari (v7) on iPhone 5S (iOS v7) (Browserstack)

***Working***
- Safari (v10) on iPhone 5S (iOS v10.2) (XCode)

**Comment by talltom** [comment]
Update, I'm now calling the Intl library from the Polyfill CDN. Website will now load on older phones (to be documented).

**Comment by talltom** [comment]
Map and cards now load (with translation) on simulated: 
- iPhone 4s (iOS 8.1) with Safari (Mobile 8) (XCode)
- iPhone 5s (iOS 7) with Safari (v7) (Browserstack)

<img width="318" alt="screen shot 2016-12-17 at 11 42 10 am" src="https://cloud.githubusercontent.com/assets/944642/21288363/211cb58e-c44f-11e6-85c3-b31f0d2753fe.png">
<img width="320" alt="screen shot 2016-12-17 at 11 42 31 am" src="https://cloud.githubusercontent.com/assets/944642/21288364/25403eb0-c44f-11e6-8417-e88aa79b95ba.png">
