### ISSUE TITLE
Include fonts; safari + old browsers issues

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#63]
Place requisite fonts in assets/*
Include in build?

**Comment by asbarve** [comment]
**Remove CDN's and include nom libraries.**

http://stackoverflow.com/questions/39271458/how-can-i-add-font-awesome-to-my-aurelia-project-using-npm 
see above link for font-awesome

https://www.npmjs.com/package/google-fonts-offline
for google fonts

**Comment by asbarve** [comment]
Need to take decision on using font cdn vs Assets

**Comment by asbarve** [comment]
Use http://fontello.com for lighter build.

**Comment by talltom** [comment]
Hi @asbarve is this fixed now, or do we still need to discuss fontello?

**Comment by asbarve** [comment]
@talltom We can move this to enhancements/beta 2: font-awesome is working but it still dumps all the symbol information in build, need to find a way to build selective fonts.

**Comment by asbarve** [comment]
Beta 1 update : Font-Awesome working , google fonts through CDN working.
Beta 2 todo: limit the font-awesome size, embed google fonts in the build?

**Comment by talltom** [comment]
OK I'm going to close this issue, as it related to a few issues, and I have opened a new enhancement request for fonts in Beta 2. Hopefully this will help keep issues clearer.

https://github.com/urbanriskmap/petabencana.id/issues/85
