### ISSUE TITLE
Get request to confirm report submission?

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#7]
The cards currently proceed directly to 'Thank you, you report has been submitted', and thereafter to petabencana.id, once the user swipes to submit.
Should there be instead a confirmation from the server that the information has been successfully received, before showing the thanks card? Else, we have a timeout function which displays an error /check internet connection msg

**Comment by abrahamq** [comment]
I don't know if this is worthwhile. If there's an internet connection problem then they have to try again? I at least think that this can be pushed until after Dec 8. @talltom thoughts?

**Comment by abrahamq** [comment]
bump? @talltom @matthewberryman @mgvarley

**Comment by talltom** [comment]
@ojha-url After a card is submitted, is receipt of card data is successful by server then a 200 status code will be returned. See https://docs.petabencana.id/routes/cards.html

**Comment by talltom** [comment]
Need a "stock image" (camera icon) for times no image available.
