### ISSUE TITLE
Remove /#/ from URL

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#71]

**Comment by talltom** [comment]
References, looks like we'll need some support from @matthewberryman server side, I haven't completely got my head around how push state works.

(1) https://discoveraurelia.com/tutorials/supporting-pushstate-nice-urls/
(2) http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/2

**Comment by matthewberryman** [comment]
I have set up cloudfront for petabencana.id as per https://keita.blog/2015/11/24/hosting-a-single-page-app-on-s3-with-proper-urls/ to support this—it's currently being deployed (ETA in a few minutes from time of this comment). It's a bit of a hack, and means that 404 error handling in #57 needs to be done by aurelia.
@mgvarley is best placed to advise on push state and error handling. Also let me know if there's a better way of doing this in cloudfront.

**Comment by mgvarley** [comment]
Hi guys - you should be able to get this working using the advice here http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/7.  So in aurelia.config:

```
  configureRouter(config) {
    ...
    config.options.pushState = true;
    config.options.root = '/';
    ...
    config.map([
```

Then in Cloudfront config you will need to redirect all 404s and 403s to /index.html and return status as 200.  @matthewberryman I see you are just doing this for 404s currently however AWS is returning a 403 if you call something it does not know about e.g. https://petabencana.id/hello - I have amended the Cloudfront config for dev to do both, if this works OK you will need to do the same for the other Cloudfront dists

**Comment by mgvarley** [comment]
Just tried this out locally with latest dev branch and can't seem to get it working, also included <base href="/"> in index.html head section as advised in the docs.  Not sure why this is not playing ball, will continue to investigate

**Comment by mgvarley** [comment]
It looks like this approach does work however the code you have for routing is then overriding and putting the # back in.  Suggest looking at <a route-href.. logic in aurelia for linking between pages.  The change to index.html required to make this work is as follows:

```
<head>
<base href="/">
...
</head>
```

**Comment by talltom** [comment]
Fixed in ef3633282bb58f955c257f02473264e1e828871d

**Comment by matthewberryman** [comment]
Reopening until I've made the corresponding 403 change in CF (soon)

**Comment by matthewberryman** [comment]
Done in our prod environment (and @mgvarley had already made the change in dev as noted). Will take a few minutes for CF to pick up the change.
