### ISSUE TITLE
move reference to API server to a config file

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#72]
and document in README.md

**Comment by talltom** [comment]
Move to routes/map/config.js

**Comment by talltom** [comment]
Also move DEFAULT_CITY etc from map.js

**Comment by matthewberryman** [comment]
@talltom does moving it under routes/map make sense given it should also be used by cards?

We may also need to have a separate hostname and path defined for image uploads because they could be handled by cloudfront+s3 separate to the API server. Depends on where the logic goes, though (do you give the image to cloudfront+s3 and then tell the API server the filename only, etc.)

**Comment by talltom** [comment]
@matthewberryman
re. config - I will discuss with @ojha-url 
re. images - I will discuss with @mgvarley as we talked about this earlier in the week
