### ISSUE TITLE
Iframe support for PetaBencana.id map

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/petabencana.id#74]
functionality for PetaBencana.id to be embedded into BPBD/similar sites using an Iframe

**Comment by talltom** [comment]
No demand for this in 2016/2017 monsoon season. Other options include using our Leaflet code and APIs to host custom maps. Seems that the ecosystem in Indonesia is happy to use data API with their own systems.

Closing for now, can reopen if we get a new request.
