### ISSUE TITLE
Map glitches

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/petabencana.id#76]
**UI**
- ~~Move city links from bottom bar to menu/options pane, remove bottom bar.~~
- ~~Add message/ prompt for city change on landing page, onLoad (unless city name is queried in url).~~
- ~~Add "floating" risk lab logo~~
- ~~Decide on legend location~~
- Add copyright data providers text to side bar/watch pane
- ~~Remove close button from options/menu panel, while options button toggles between 3-bars & cross icon~~
- ~~Resolve loading time/tiles.~~

**js**
- ~~Update city name in browser url when user hits geolocate button and location is within a supported city~~
- ~~Confirm if `map.flyToBounds()` and `map.setMaxBounds()` can be called synchronously, else will have to give up flyTo function and resort to spontaneous switches in map view. @talltom ?
flyTo(center), min/max zoom and max bounds work well together; while flyToBounds is not compatible with either zoom controls or restricting pan bounds.~~

**Comment by asbarve** [comment]
look into using D3 library for landing page.

**Comment by talltom** [comment]
Chain moveend to flyto for synchronous https://github.com/Leaflet/Leaflet/pull/3293?

**Comment by talltom** [comment]
@ojha-url & @asbarve & I agree to remove FlyTo function.

**Comment by talltom** [comment]
Interesting legend UI https://www.trulia.com/MA/Cambridge/

**Comment by talltom** [comment]
Map UI side panel proposal:
- hamburger / arrow icon, opens
   . map (city / map)
   . video (pin)
   . about (question mark / info)

**Comment by ojha-url** [comment]
Legends for maps to be placed in the map tab of the side bar, decided by me & @talltom.

**Comment by ojha-url** [comment]
flyTo(clientLocation), setView(), fitBounds(), flyToBounds(), all fail as they conflict with setMaxBounds() assigned to map on changeCity(); see #141. 
Reopening this to take a decision whether we want to restrict map panning outside of a city's bounds. @talltom?
