### ISSUE TITLE
Get rid of CDNs 

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/petabencana.id#8]
We need to get rid of the CDNs and use locally hosted libraries?

**Comment by mgvarley** [comment]
Yup, you should be able import any dependencies you need using the approach I outlined in Issue #12, once a dependency is installed (`npm install xxx`) and the configured in aurelia.json it will be bundled at build time and minified.  You might want to still use a CDN for something that not all users will need e.g. the polyfill service

**Comment by matthewberryman** [comment]
Yes I'm in favour of locally hosted libraries (which go out on our setup in CloudFront CDN), for a few reasons:
1. If you use someone else's CDN then you need to worry about [subresource integtrity](https://www.troyhunt.com/protecting-your-embedded-content-with-subresource-integrity-sri/).
2. You've then got no control over their CDN, e.g. if they remove a version, or if they mess up their CDN.
3. Stuff on Google's CDN is blocked in China, so for development and maintenance while I'm in China, or demoing stuff there, or future use there, it's a consideration.

**Comment by mgvarley** [comment]
Aurelia (and most other SPA frameworks) assume that would will bundle everything at build time (npm run build) and it generates the following - this is the entirety of your application.  The index.html is very simple, it setups the viewport and a couple of other bits and then everything else you write, .html and .js pages and all config files are compiled into the app-bundle.  Any third party dependencies that you npm install and then reference in aurelia.json are compiled into the vendor-bundle file.  The only CDN I have referenced is cdn.polyfill which will be lazily loaded just when a user has an old browser that does not support ES6 (hopefully the great firewall is ok with this CDN!).  The only extra folder you might have (that I haven’t shown in this simple example) is an assets folder containing static img files (there should be no js files in this).  You will see that a unique id is assigned to the two .js bundles, this is is to prevent Cloudfront / browser caching and your updates not being picked up.


Hope this all makes sense, happy to walk you through this process.


m

**Comment by matthewberryman** [comment]
Yeah that's what I'd figured I was just giving more justification for doing it :)

**Comment by abrahamq** [comment]
Okay, awesome! Happy to hear this is fixed because of our Aurelia decision.
