### ISSUE TITLE
Translation / Multiple Language Support

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#81]
- add a language option to map menu
- use setLocale() to change language
- reference: https://mttmccb.github.io/starting-with-aurelia-i18n/

**Comment by ojha-url** [comment]
setLocale() to change language on the fly doesn't work, investigate other methods.

**Comment by talltom** [comment]
maps: - force refresh (as per existing petajakarta.org functionality)
cards:- button on first card to select language, and force refresh of card

Need to change global variable which is stored within main.js.

**Comment by talltom** [comment]
@ojha-url to test manual switching of locale/.json text content files, without i18n plugin.

**Comment by ojha-url** [comment]
Implemented manual switching of locales with aurelia functionality & custom code.
