### ISSUE TITLE
Unsupported features notification? Or decide cut-off for browsers/versions

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/petabencana.id#83]
- Translations (with intl lib CDN) not working on android browser, (but does not make the app crash after removing polyfill features query). 
- Photo upload using `<input type="file" accept="image/">` not working on android browser (all versions). Also `<canvas>` not supported on non-html5 compatible browsers.

Suggestions: 
- Since photo is a non-mandatory input, we can notify user with a 'photo upload not supported by your browser' like msg. 
- Same for translations? (but will still require to hard-code back-up strings for each text that is being translated.)

**Comment by ojha-url** [comment]
also add geolocation notifications

**Comment by talltom** [comment]
- refer to #81 regarding translation
- for non HTML5 browsers, photo upload screen will show message "browser not supported"

**Comment by ojha-url** [comment]
Test for canvas support:
http://diveinto.html5doctor.com/detect.html#canvas
