### ISSUE TITLE
Visual Style Guide

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/petabencana.id#9]
**3 sections for each : website, cards, promotional material**

1. Fonts
	font families
	font color
2. color palettes
3. Icons and logos
4. elements -
5. Website specific - buttons, popups

**Comment by abrahamq** [comment]
I think this should go in the userdesign repo? https://github.com/urbanriskmap/userdesign

**Comment by abrahamq** [comment]
I'm closing because the style guide is close to finished- also all future issues should go in the userdesign repo.
