### ISSUE TITLE
Final page says to check twitter irrespective of source

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#93]
When trying out [reporting via SMS](https://github.com/urbanriskmap/cognicity-reports-twilio/pull/1) I noticed the final page says to "check twitter for confirmation".

**Comment by talltom** [comment]
We can use the initial get request for card validation, which returns the network name (e.g. SMS).
- need to pass this through from cards.js to thanks card (e.g. see error card for examples) at  https://github.com/urbanriskmap/petabencana.id/blob/dev/src/routes/cards/cards.js#L66

**Comment by talltom** [comment]
Fixed this one specially for @matthewberryman ahead of launch.
