### ISSUE TITLE
Aurelia watch gobbles Mapbox views faster than Pacman

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#94]
`npm start` executes `au run --env dev --watch`
- every time a file change is detected a page refresh is called. If this page contains a map then new map tiles are requested from Mapbox

<img width="1002" alt="screen shot 2017-01-05 at 11 19 46 am" src="https://cloud.githubusercontent.com/assets/944642/21687969/2ce718b6-d339-11e6-97b8-5a1e5b8852d8.png">

**Comment by MaanasaPriyaa** [comment]
Haha, I see you're having fun.

**Comment by matthewberryman** [comment]
[![screenshot 2017-01-06 06 26 01](https://cloud.githubusercontent.com/assets/2288238/21694400/2481d1de-d3d9-11e6-9804-072b5bcdc016.png)](http://pacman.platzh1rsch.ch/)

**Comment by matthewberryman** [comment]
I guess just disable aurelia watch then, and communicate to users?

**Comment by talltom** [comment]
We've switched to an alternative tile provider for development work, which is coded as an Aurelia environment variable, so prod builds will use our custom MapBox layers.
